# values.yaml
replicaCount: 2

accelerationDv:
  name: acceleration-dv
  image: pramodprasanna/pro-acceleration-dv:1.0
  port: 3001

accelerationA:
  name: acceleration-a
  image: pramodprasanna/pro-acceleration-a:1.0
  port: 3002

accelerationCalc:
  name: acceleration-calc
  image: pramodprasanna/pro-acceleration:1.0
  port: 3000

service:
  port: 3000

serviceAccount:
  create: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10

ingress:
  enabled: true
